
image:
  name: hashicorp/terraform:light
  entrypoint:
    - '/usr/bin/env'
    - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'

before_script:
  - rm -rf .terraform
  - terraform --version
  - mkdir -p ../creds
  - echo $SERVICEACCOUNT | base64 -d > ../creds/serviceaccount.json
  - terraform init terraform/

stages:
  - validate
  - plan
  - apply
  - destroy

validate:
  stage: validate
  script:
    - terraform validate terraform/

plan:
  stage: plan
  script:
    - terraform plan terraform/ -out "planfile"
  dependencies:
    - validate
  artifacts:
    paths:
      - planfile

apply:
  stage: apply
  script:
    - terraform apply terraform/ -input=false "planfile"
  dependencies:
    - plan
  when: manual

# install kubectl
# install docker
# connect cluster
# deploy goweb


destroy:
  stage: destroy
  script:
    - terraform destroy terraform/ -auto-approve
  when: manual